<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
        use HasApiTokens, HasFactory, Notifiable;

            /**
                 * The attributes that are mass assignable.
                      *
                           * @var list<string>
                                */
                                    protected $fillable = [
                                            'name',
                                                    'email',
                                                            'password',
                                                                    'role',
                                                                            'etablissement',
                                                                                ];

                                                                                    /**
                                                                                         * The attributes that should be hidden for serialization.
                                                                                              *
                                                                                                   * @var list<string>
                                                                                                        */
                                                                                                            protected $hidden = [
                                                                                                                    'password',
                                                                                                                            'remember_token',
                                                                                                                                ];

                                                                                                                                    /**
                                                                                                                                         * Get the attributes that should be cast.
                                                                                                                                              *
                                                                                                                                                   * @return array<string, string>
                                                                                                                                                        */
                                                                                                                                                            protected function casts(): array
                                                                                                                                                                {
                                                                                                                                                                        return [
                                                                                                                                                                                    'email_verified_at' => 'datetime',
                                                                                                                                                                                                'password' => 'hashed',
                                                                                                                                                                                                        ];
                                                                                                                                                                                                            }

                                                                                                                                                                                                                /**
                                                                                                                                                                                                                     * Vérifie si l'utilisateur est un formateur.
                                                                                                                                                                                                                          */
                                                                                                                                                                                                                              public function isFormateur(): bool
                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                          return $this->role === 'formateur';
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                                                       * Vérifie si l'utilisateur est un stagiaire.
                                                                                                                                                                                                                                                            */
                                                                                                                                                                                                                                                                public function isStagiaire(): bool
                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                            return $this->role === 'stagiaire';
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                         * Classes créées par le formateur.
                                                                                                                                                                                                                                                                                              */
                                                                                                                                                                                                                                                                                                  public function classesFormateur(): HasMany
                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                              return $this->hasMany(Classe::class, 'formateur_id');
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                      /**
                                                                                                                                                                                                                                                                                                                           * Classes auxquelles le stagiaire appartient.
                                                                                                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                                                                                                    public function classesStagiaire(): BelongsToMany
                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                return $this->belongsToMany(Classe::class, 'classe_stagiaire', 'stagiaire_id', 'classe_id')
                                                                                                                                                                                                                                                                                                                                                                    ->withTimestamps();
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                                                 * Présentations créées par le formateur.
                                                                                                                                                                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                                                                                                                                                                          public function presentations(): HasMany
                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                      return $this->hasMany(Presentation::class, 'formateur_id');
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                              /**
                                                                                                                                                                                                                                                                                                                                                                                                                   * Assignations du stagiaire.
                                                                                                                                                                                                                                                                                                                                                                                                                        */
                                                                                                                                                                                                                                                                                                                                                                                                                            public function assignations(): HasMany
                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                        return $this->hasMany(Assignation::class, 'stagiaire_id');
                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                     * Uploads du stagiaire.
                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
                                                                                                                                                                                                                                                                                                                                                                                                                                                              public function uploads(): HasMany
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return $this->hasMany(Upload::class, 'stagiaire_id');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              